COMPONENT=MoteAppC
CFLAGS += -IMeasure
CFLAGS += -ILcdControl
CFLAGS += -ILcdMenu
CFLAGS += -INodeTools
CFLAGS += -INodeComm
CFLAGS += -I$(TOSDIR)/lib/net
CFLAGS += -I$(TOSDIR)/lib/net/drip
CFLAGS += -I$(TOSDIR)/lib/net/le
CFLAGS += -I$(TOSDIR)/lib/net/ctp
CFLAGS += -Wnesc-all #zusätzliche Warnings aus nesc
CFLAGS += -DUSE_UART0 #LCD an UART0
include $(MAKERULES)

