COMPONENT=MoteAppC
#printf arbeitet (leider) nicht mit der MoteConsole zusammen
#CFLAGS += -I$(TOSDIR)/lib/printf
#CFLAGS += -DNEW_PRINTF_SEMANTICS
CFLAGS += -IMeasure
CFLAGS += -ILcdControl
CFLAGS += -ILcdMenu
include $(MAKERULES)

