COMPONENT=MonitorAppC
CFLAGS += -I../
CFLAGS += -I../Measure
CFLAGS += -I../LcdControl
CFLAGS += -I../LcdMenu
CFLAGS += -I../NodeTools
CFLAGS += -I../NodeComm
CFLAGS += -I$(TOSDIR)/lib/net
CFLAGS += -I$(TOSDIR)/lib/net/drip
CFLAGS += -I$(TOSDIR)/lib/net/le
CFLAGS += -I$(TOSDIR)/lib/net/ctp
CFLAGS += -Wnesc-all #zusätzliche Warnings aus nesc
CFLAGS += -DUSE_UART1 #LCD an UART1
include $(MAKERULES)

