COMPONENT=ProjectRssiAppC
CFLAGS += -I$(TOSDIR)/lib/printf
CFLAGS += -I..
CFLAGS += -I../Measure
CFLAGS += -I../NodeTools
CFLAGS += -I$(TOSDIR)/lib/net
CFLAGS += -I$(TOSDIR)/lib/net/drip
CFLAGS += -I$(TOSDIR)/lib/net/le
CFLAGS += -I$(TOSDIR)/lib/net/ctp

include $(MAKERULES)

