COMPONENT=PcMoteAppC
CFLAGS += -I..
CFLAGS += -I../NodeTools
CFLAGS += -I../NodeComm
CFLAGS += -I$(TOSDIR)/lib/net
CFLAGS += -I$(TOSDIR)/lib/net/drip
CFLAGS += -I$(TOSDIR)/lib/net/le
CFLAGS += -I$(TOSDIR)/lib/net/ctp
CFLAGS += -Wnesc-all #zusätzliche Warnings aus nesc
include $(MAKERULES)

